#!/usr/bin/env python3

import os.path

if os.path.isfile("roles.html"):
  os.remove("roles.html")

with open("roles.html", "w") as html, open("roles.txt", 'r') as txt, open("../menu.html", 'r') as menu:
  menu = "".join(menu.readlines())
  title = txt.readline().strip()
  roles = txt.readlines()[1:]
  num_roles = len(roles)
  currmax = 0
  actors = []
  names = []

  for role in roles:
    splt = role.split(" - ")
    if (splt[0] is "\n"):
      names.append(None)
      actors.append(None)
      continue
    name = splt[0]
    names.append(name)
    actors.append(splt[1])

    namelen = len(name)
    if (namelen > currmax):
      currmax = namelen

  for i in range(num_roles):
    if (names[i] is not None): 
      required_spaces = currmax - len(names[i])
      roles[i] = names[i] + (" " * required_spaces) + " - " + actors[i]

  roles = "".join(roles)
  html.write(f"""
<!DOCTYPE html>
<html lang=\'ru\'>
  <head>
    <title>{title}</title>
    <link rel=\"stylesheet\" href=\"../../styles.css\">
    <link rel=\"stylesheet\" href=\"../txtstyle.css\">
  </head>
  <body>
      <meta charset=utf-8>
       <center>
         <h1>{title}</h1>
       </center>
      <div id="mySidenav" class="sidenav">
         <div class="insidenav">{menu}</div>
       </div>
     <div class=\"row\">
       <div class=\"card\">
         <h2>Распределение ролей</h2>
         <div class=\"textbox\">
           <p>{roles}</p>
        </div>
      </div>
  </body>
</html>""")

